package com.movil.arbnb

enum class Screen {
    LOGIN, REGISTRATION, SUCCESS_REGISTRATION, HOME, PROPERTY_DETAIL, PROFILE, MY_PROPERTIES, MY_RESERVATIONS, ADD_RESERVATION, MESSAGES, CHAT_DETAIL, FAVORITES, CONFIRM_PAY
}
